### ISSUE TITLE
Should all files be processed when the license changes?

### ISSUE THREAD

**Issue by fbiville** [fbiville/headache#29]
As it is implemented today, `headache` processes only the files which have changed between two runs. While it's a sensible approach in the nominal case, I am not sure about the best course of action if the license has changed in between.

 - Shall all the files be scanned again?
 - What happens to the potentially existing copyright years in the detected header in that case? Are they reset or preserved as explained [here](https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated) (<-- which is `headache`'s approach right now)?

I think I'll need @glyn expertise and experience on this :)
Happy new year by the way! 🎉

**Comment by glyn** [comment]
IANAL, but I don't think a change in license should affect the years for which copyright is asserted. Of course, the license header needs to be switched to the new license in all files and whether _that_ counts as a significant change (and require updating the later year of the date range) is a question for a lawyer. I would think it depends on whether the license header is really part of the copyrighted file. But how can it be, since the license header itself wasn't authored by the copyright author? So my non-lawyer guess would be that you don't need to change the dates when you switch licenses.

Oh, and Happy New Year!
